project:
  type: website
  output-dir: docs

website:
  title: "Manual de SPSS"
  navbar:
    left:
      - text: Inicio
        href: index.qmd
      - text: Procesamiento de bases
        menu:
          - href: import.qmd
            text: Importación de bases
          - href: procesamiento.qmd
            text: Recodificación
          - href: proc_mrsets.qmd
            text: Respuestas múltiples
      - text: Estadística univariada
        menu:
          - href: desc_unica.qmd
            text: Respuesta única
          - href: desc_mrsets.qmd
            text: Respuestas múltiples
      - text: Estadística bivariada
        menu:
          - href: chi2.qmd
            text: Chi-cuadrado
      - text: Gráficos
        # menu:
        #   - href: graficos.qmd
        #     text: Gráficos

format:
  html:
    theme: cosmo
    toc: true
